services:
  schema-register:
    build:
      context: ./src/services/schema-register
    ports:
      - "8000:8000"


  cluster-manager:
    build:
      context: ./src/services/cluster-manager
    ports:
      - "5000:5000"

  ingestor-1:
    build:
      context: ./src/services/ingestor
    environment:
      - NODE_ADDR=http://ingestor-1:4001
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
      - INGESTOR_ADDR=:4001
    ports:
      - "4001:4001"
    depends_on:
      - cluster-manager

  ingestor-2:
    build:
      context: ./src/services/ingestor
    environment:
      - NODE_ADDR=http://ingestor-2:4002
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
      - INGESTOR_ADDR=:4002
    ports:
      - "4002:4002"
    depends_on:
      - cluster-manager

  client-1:
    build:
      context: ./src/services/client
    command: ["./client", "--batch", "4000", "--interval", "10"]
    depends_on:
      - ingestor

  client-2:
    build:
      context: ./src/services/client
    command:
      [
        "./client",
        "--batch",
        "4000",
        "--interval",
        "10",
        "--format",
        "proto",
      ]
    depends_on:
      - ingestor

  client-3:
    build:
      context: ./src/services/client
    command:
      [
        "./client",
        "--batch",
        "4000",
        "--interval",
        "10",
        "--format",
        "avro",
      ]
    depends_on:
      - ingestor

  client-4:
    build:
      context: ./src/services/client
    command:
      [
        "./client",
        "--batch",
        "4000",
        "--interval",
        "10",
        "--format",
        "raw",
      ]
    depends_on:
      - ingestor
