services:
  schema-validator:
    build:
      context: ./src/services/schema-validator

  cluster-manager:
    build:
      context: ./src/services/cluster-manager
    ports:
      - "5000:5000"

  storage-1:
    build:
      context: ./src/services/storage
    environment:
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
    depends_on:
      - cluster-manager

  storage-2:
    build:
      context: ./src/services/storage
    environment:
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
    depends_on:
      - cluster-manager

  storage-3:
    build:
      context: ./src/services/storage
    environment:
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
    depends_on:
      - cluster-manager

  ingestor-1:
    build:
      context: ./src/services/ingestor
    environment:
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
      - APP_VERSION=Ingestor 1.20.0
    depends_on:
      - cluster-manager
      - storage-1
      - storage-2
      - storage-3

  ingestor-2:
    build:
      context: ./src/services/ingestor
    environment:
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
      - APP_VERSION=Ingestor 1.20.0
    depends_on:
      - cluster-manager
      - storage-1
      - storage-2
      - storage-3
  # ingestor-3:
  #   build:
  #     context: ./src/services/ingestor
  #   environment:
  #     - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
  #   depends_on:
  #     - cluster-manager
  #     - storage-1
  #     - storage-2
  #     - storage-3

  query:
    build:
      context: ./src/services/query
    ports:
      - "8000:8000"
    environment:
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
    depends_on:
      - cluster-manager
      - storage-1
      - storage-2
      - storage-3

  client-1:
    build:
      context: ./src/services/client
    command:
      ["./client", "--batch", "3000", "--interval", "10", "--format", "proto"]
    depends_on:
      - ingestor-1
      - ingestor-2

  # client-2:
  #   build:
  #     context: ./src/services/client
  #   command:
  #     ["./client", "--batch", "3000", "--interval", "10", "--format", "proto"]
  #   depends_on:
  #     - ingestor-1
  #     - ingestor-2
  #     - ingestor-3
