services:
  schema-validator:
    build:
      context: ./src/services/schema-validator

  cluster-manager:
    build:
      context: ./src/services/cluster-manager
    ports:
      - "5000:5000"

  storage-1:
    build:
      context: ./src/services/storage
    environment:
      - STORAGE_NAME=storage-1
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
    depends_on:
      - cluster-manager

  storage-2:
    build:
      context: ./src/services/storage
    environment:
      - STORAGE_NAME=storage-2
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
    depends_on:
      - cluster-manager

  storage-3:
    build:
      context: ./src/services/storage
    environment:
      - STORAGE_NAME=storage-3
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
    depends_on:
      - cluster-manager

  ingestor-1:
    build:
      context: ./src/services/ingestor
    environment:
      - NODE_ADDR=http://ingestor-1:4001
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
    depends_on:
      - cluster-manager
      - storage-1
      - storage-2
      - storage-3

  ingestor-2:
    build:
      context: ./src/services/ingestor
    environment:
      - NODE_ADDR=http://ingestor-2:4002
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
    depends_on:
      - cluster-manager
      - storage-1
      - storage-2
      - storage-3

  client-1:
    build:
      context: ./src/services/client
    command: ["./client", "--batch", "2500", "--interval", "10"]
    depends_on:
      - ingestor-1
      - ingestor-2

  client-2:
    build:
      context: ./src/services/client
    command:
      ["./client", "--batch", "2500", "--interval", "10", "--format", "raw"]
    depends_on:
      - ingestor-1
      - ingestor-2
