services:
  cluster-manager:
    build:
      context: ./src/services/cluster-manager

  schema-validator:
    build:
      context: ./src/services/schema-validator
    environment:
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
    depends_on:
      - cluster-manager

  storage-1:
    build:
      context: ./src/services/storage
    environment:
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
    depends_on:
      - cluster-manager

  storage-2:
    build:
      context: ./src/services/storage
    environment:
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
    depends_on:
      - cluster-manager

  storage-3:
    build:
      context: ./src/services/storage
    environment:
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
    depends_on:
      - cluster-manager

  ingestor-1:
    build:
      context: ./src/services/ingestor
    environment:
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
      - APP_VERSION=Ingestor 1.21.0
    depends_on:
      - cluster-manager
      - storage-1
      - storage-2
      - storage-3

  ingestor-2:
    build:
      context: ./src/services/ingestor
    environment:
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
      - APP_VERSION=Ingestor 1.22.0
    depends_on:
      - cluster-manager
      - storage-1
      - storage-2
      - storage-3

  query:
    build:
      context: ./src/services/query
    ports:
      - "8000:8000"
    environment:
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
    depends_on:
      - cluster-manager
      - storage-1
      - storage-2
      - storage-3
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 256M

  metrics-aggregator:
    build:
      context: ./src/services/metrics-aggregator
    ports:
      - "3000:3000"
    environment:
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
    depends_on:
      - cluster-manager
      - ingestor-1
      - ingestor-2
      - storage-1
      - storage-2
      - storage-3

  client-1:
    build:
      context: ./src/services/client
    command:
      ["./client", "--batch", "500", "--interval", "10", "--format", "proto"]
    environment:
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
    depends_on:
      - cluster-manager
      - ingestor-1
      - ingestor-2

  client-2:
    build:
      context: ./src/services/client
    command:
      ["./client", "--batch", "500", "--interval", "10", "--format", "json"]
    environment:
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
    depends_on:
      - cluster-manager
      - ingestor-1
      - ingestor-2

  client-query:
    build:
      context: ./src/services/client
    command:
      [
        "./client",
        "--queryload",
        "--queryconcurrency",
        "2",
        "--workloadlimit",
        "100",
      ]
    environment:
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
    depends_on:
      - cluster-manager
      - query

  client-validation:
    build:
      context: ./src/services/client
    command: ["./client", "--validationload", "--queryconcurrency", "2"]
    environment:
      - CLUSTER_MANAGER_ADDR=http://cluster-manager:5000
    depends_on:
      - cluster-manager
      - schema-validator
