version: "3"

services:
  go-ingestor:
    build:
      context: ./src/services/go-ingestor
    volumes:
      - ./data/:/app/data
    ports:
      - "3000:3000"
  go-client-1:
    build:
      context: ./src/services/go-client
    command: ["./go-client", "--batch", "500", "--interval", "10"]
    depends_on:
      - go-ingestor
  go-client-2:
    build:
      context: ./src/services/go-client
    command: ["./go-client", "--batch", "500", "--interval", "10"]
    depends_on:
      - go-ingestor
